# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Demo Book
author: \'24 HRL Clinic Team
logo: hrl-logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  # NB: non-GitHub URLs likely won't work. see https://github.com/executablebooks/jupyter-book/issues/1964#issuecomment-1474104807 for some suggestions
  url: https://github.com/trishanamruthur/HRL-Labs-Clinic  # Online location of your book
  path_to_book: HRL-demo-book  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  notebook_interface: "jupyterlab"  # or "classic" (will support markdown notebooks)
  jupyterhub_url: "https://strong-honeybee-virtually.ngrok-free.app/"


# require js for interactive plotting
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
